import { z } from 'zod';

export const productSchema = z.object({
  productId: z.string(),
  name: z.string().min(1, 'Product name is required'),
  sku: z.string().min(1, 'SKU is required'),
  category: z.string().min(1, 'Category is required'),
  stock: z.number().default(0),
  minStock: z.number().default(0),
  purchasePrice: z.number().default(0),
  sellingPrice: z.number().default(0),
  gstRate: z.number().default(0),
  hsn: z.string().optional(),
  version: z.number().optional(),
  deviceId: z.string().optional(),
});

export const customerSchema = z.object({
  customerId: z.string(),
  name: z.string().min(1, 'Customer name is required'),
  phone: z.string().min(10, 'Valid phone number is required'),
  email: z.string().email('Invalid email address').or(z.string().length(0)).optional().nullable(),
  address: z.string().optional().nullable(),
  state: z.string().optional().nullable(),
  gstin: z.string().optional().nullable(),
  outstanding: z.number().default(0),
  allowedStaffActions: z.array(z.string()).optional(),
  version: z.number().optional(),
  deviceId: z.string().optional(),
});

export const supplierSchema = z.object({
  supplierId: z.string(),
  name: z.string().min(1, 'Supplier name is required'),
  phone: z.string().min(10, 'Valid phone number is required'),
  email: z.string().email('Invalid email address').or(z.string().length(0)).optional().nullable(),
  address: z.string().optional().nullable(),
  gstin: z.string().optional().nullable(),
  outstanding: z.number().default(0),
  version: z.number().optional(),
  deviceId: z.string().optional(),
});

const invoiceItemSchema = z.object({
  productId: z.string(),
  productName: z.string(),
  quantity: z.number().min(1),
  price: z.number().min(0),
  discount: z.number().default(0),
  gstRate: z.number().default(0),
  gstAmount: z.number().default(0),
  subtotal: z.number(),
  total: z.number(),
});

export const invoiceSchema = z.object({
  invoiceId: z.string(),
  invoiceNumber: z.string(),
  date: z.string(),
  customerId: z.string(),
  customerName: z.string(),
  items: z.array(invoiceItemSchema),
  subtotal: z.number(),
  discountTotal: z.number(),
  gstTotal: z.number(),
  grandTotal: z.number(),
  amountPaid: z.number(),
  balanceDue: z.number(),
  paymentStatus: z.enum(['Paid', 'Partial', 'Unpaid']),
  paymentMethod: z.string().optional().nullable(),
  referenceNumber: z.string().optional().nullable(),
  dueDate: z.string().optional().nullable(),
  notes: z.string().optional().nullable(),
  showSignature: z.boolean().default(false),
  version: z.number().optional(),
  deviceId: z.string().optional(),
});

const quotationItemSchema = z.object({
  productId: z.string(),
  productName: z.string(),
  quantity: z.number().min(1),
  price: z.number().min(0),
  discount: z.number().default(0),
  gstRate: z.number().default(0),
  gstAmount: z.number().default(0),
  subtotal: z.number(),
  total: z.number(),
});

export const quotationSchema = z.object({
  quotationId: z.string(),
  quotationNumber: z.string(),
  date: z.string(),
  validUntil: z.string(),
  customerId: z.string(),
  customerName: z.string(),
  items: z.array(quotationItemSchema),
  subtotal: z.number(),
  discountTotal: z.number(),
  gstTotal: z.number(),
  grandTotal: z.number(),
  status: z.enum(['Draft', 'Sent', 'Approved', 'Declined', 'Converted']),
  convertedInvoiceId: z.string().optional().nullable(),
  notes: z.string().optional().nullable(),
  version: z.number().optional(),
  deviceId: z.string().optional(),
});

const purchaseItemSchema = z.object({
  productId: z.string(),
  productName: z.string(),
  quantity: z.number().min(1),
  price: z.number().min(0),
  gstRate: z.number().default(0),
  gstAmount: z.number().default(0),
  subtotal: z.number(),
  total: z.number(),
  discount: z.number().optional().nullable(),
});

export const purchaseSchema = z.object({
  purchaseId: z.string(),
  purchaseNumber: z.string(),
  date: z.string(),
  supplierId: z.string(),
  supplierName: z.string(),
  items: z.array(purchaseItemSchema),
  subtotal: z.number(),
  gstTotal: z.number(),
  grandTotal: z.number(),
  amountPaid: z.number(),
  balanceDue: z.number(),
  paymentStatus: z.enum(['Paid', 'Partial', 'Unpaid']),
  paymentMethod: z.string().optional().nullable(),
  notes: z.string().optional().nullable(),
  version: z.number().optional(),
  deviceId: z.string().optional(),
});

export const paymentSchema = z.object({
  paymentId: z.string(),
  date: z.string(),
  type: z.enum(['CustomerReceipt', 'SupplierPayment']),
  contactId: z.string(),
  contactName: z.string(),
  amount: z.number().min(0.01, 'Payment amount must be greater than zero'),
  paymentMethod: z.enum(['UPI', 'Cash', 'Bank Transfer', 'Cheque']),
  referenceNumber: z.string().optional().nullable(),
  notes: z.string().optional().nullable(),
  version: z.number().optional(),
  deviceId: z.string().optional(),
});

export const expenseSchema = z.object({
  expenseId: z.string(),
  date: z.string(),
  category: z.string().min(1, 'Category is required'),
  payee: z.string().min(1, 'Payee is required'),
  amount: z.number().min(0.01, 'Expense amount must be greater than zero'),
  paymentMethod: z.enum(['UPI', 'Cash', 'Bank Transfer', 'Cheque']),
  status: z.enum(['Paid', 'Due']),
  dueDate: z.string().optional().nullable(),
  referenceNumber: z.string().optional().nullable(),
  notes: z.string().optional().nullable(),
  version: z.number().optional(),
  deviceId: z.string().optional(),
});

export const settingsSchema = z.object({
  businessName: z.string().min(1, 'Business name is required'),
  ownerName: z.string().min(1, 'Owner name is required'),
  gstin: z.string().optional().nullable(),
  panNumber: z.string().optional().nullable(),
  businessType: z.string().optional().nullable(),
  phone: z.string().min(10, 'Valid phone number is required'),
  alternatePhone: z.string().optional().nullable(),
  email: z.string().email('Invalid email address').or(z.string().length(0)).optional().nullable(),
  website: z.string().optional().nullable(),
  addressLine1: z.string().optional().nullable(),
  addressLine2: z.string().optional().nullable(),
  city: z.string().optional().nullable(),
  taluka: z.string().optional().nullable(),
  district: z.string().optional().nullable(),
  state: z.string().optional().nullable(),
  pincode: z.string().optional().nullable(),
  address: z.string().optional().nullable(),
  logo: z.string().optional().nullable(),
  watermarkLogo: z.string().optional().nullable(),
  signature: z.string().optional().nullable(),
  bankName: z.string().optional().nullable(),
  accountHolderName: z.string().optional().nullable(),
  accountNumber: z.string().optional().nullable(),
  ifscCode: z.string().optional().nullable(),
  branchName: z.string().optional().nullable(),
  upiId: z.string().optional().nullable(),
  invoicePrefix: z.string().default('INV-'),
  purchasePrefix: z.string().default('PUR-'),
  quotationPrefix: z.string().default('QT-'),
  financialYear: z.string().optional().nullable(),
  defaultTerms: z.string().optional().nullable(),
  invoiceTerms: z.string().optional().nullable(),
  quotationTerms: z.string().optional().nullable(),
  purchaseTerms: z.string().optional().nullable(),
  footerMessage: z.string().optional().nullable(),
  showLogo: z.boolean().default(true),
  showGstin: z.boolean().default(true),
  showAddress: z.boolean().default(true),
  showContact: z.boolean().default(true),
  showBankDetails: z.boolean().default(true),
  showTerms: z.boolean().default(true),
  theme: z.enum(['light', 'dark', 'system']).default('light'),
  currencySymbol: z.string().default('₹'),
  dateFormat: z.string().default('DD/MM/YYYY'),
  showLowStockAlert: z.boolean().default(true),
  showOutOfStockAlert: z.boolean().default(true),
  version: z.number().optional(),
  deviceId: z.string().optional(),
});
